### ISSUE TITLE
Doesn't work on inline CSS background images

### ISSUE THREAD

**Issue by berend-de-jong** [amritb/LocalAssets#2]
Works:
`<img src="http://domain.dev/image.jpg">`

Doesn't work:
`<div style="background-image: url( 'http://domain.dev/image.jpg' );"></div>`

**Comment by amritb** [comment]
Thanks for the contribution @Frique! Already merged your changes.

**Comment by berend-de-jong** [comment]
Now if only we can replace the URLs in CSS files...

**Comment by amritb** [comment]
Haha. True!
